Repository Fenrir-04/Algo-Media, pull requests merged in 2023-07, with the labels that each got.

#168 added toast errors
  package-lock.json
  package.json
  src/components/Auth/Login.jsx
  src/components/Auth/Signup.jsx
  src/components/VoiceSearch.jsx
  yarn.lock
Labels: gssoc23, level2

#167 Add Confirm Password Field
  src/components/Auth/Signup.jsx
Labels: gssoc23, level3

#179 changed the background color of scroll to top button
  package-lock.json
  src/components/TopButton.css
  yarn.lock
Labels: gssoc23, level1
