Repository Fenrir-04/Algo-Media, pull requests merged in 2023-06, with the labels that each got.

#98 Refactor: use loaders
  src/App.jsx
  src/components/ChannelDetail.jsx
  src/components/Sidebar.jsx
  src/components/VideoDetail.jsx
Labels: gssoc23, level2

#110 #105 Old issue bot added
  .github/workflows/close_old_issues.yaml
Labels: gssoc23

#111 #104 depandabot Added
  .github/dependabot.yml
Labels: gssoc23, level1

#94 added back to top button
  README.md
Labels: gssoc23, level1

#136 Lazy loading added
  src/App.jsx
  src/components/index.js
Labels: gssoc23, level1

#152 feat: watchlist for videos
  src/App.jsx
  src/components/Feed.jsx
  src/components/Sidebar.jsx
  src/components/VideoCard.jsx
  src/components/VideoDetail.jsx
  src/components/Videos.jsx
  yarn.lock
Labels: gssoc23, level2
